apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        tier: hello
    spec:
      containers:
      - name: hello
        image: pjbear/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: hello
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: hello
    tier: hello
  type: LoadBalancer
